
import { createClient } from '@supabase/supabase-js';
import { RedeemCode } from '../types';

/**
 * PRODUCTION SETUP - RUN THIS IN SUPABASE SQL EDITOR:
 * 
 * CREATE TABLE redeem_codes (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   code TEXT NOT NULL,
 *   reward TEXT,
 *   region TEXT NOT NULL,
 *   hour_key TEXT NOT NULL,
 *   category TEXT,
 *   slug TEXT UNIQUE,
 *   status TEXT DEFAULT 'Working',
 *   probability INTEGER DEFAULT 99,
 *   recent_claims INTEGER DEFAULT 0,
 *   likes INTEGER DEFAULT 0,
 *   citations JSONB,
 *   created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
 * );
 * 
 * CREATE TABLE sync_logs (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   region TEXT,
 *   hour_key TEXT,
 *   synced_at TIMESTAMP WITH TIME ZONE DEFAULT now()
 * );
 */

const supabaseUrl = process.env.SUPABASE_URL || '';
const supabaseKey = process.env.SUPABASE_ANON_KEY || '';

const isSupabaseConfigured = supabaseUrl.includes('supabase.co') && supabaseKey.length > 10;

export const supabase = isSupabaseConfigured 
  ? createClient(supabaseUrl, supabaseKey)
  : null;

export const supabaseService = {
  isConnected(): boolean {
    return !!supabase;
  },

  async getGlobalCodes(region: string, hourKey: string): Promise<RedeemCode[] | null> {
    if (!supabase) return null;
    
    try {
      const { data, error } = await supabase
        .from('redeem_codes')
        .select('*')
        .eq('region', region)
        .eq('hour_key', hourKey);

      if (error) return null;
      if (!data || data.length === 0) return null;

      return this.mapSupabaseData(data);
    } catch (e) {
      return null;
    }
  },

  async getLatestAvailableCodes(region: string): Promise<RedeemCode[] | null> {
    if (!supabase) return null;
    
    try {
      const { data, error } = await supabase
        .from('redeem_codes')
        .select('*')
        .eq('region', region)
        .order('id', { ascending: false })
        .limit(12);

      if (error || !data || data.length === 0) return null;
      return this.mapSupabaseData(data);
    } catch (e) {
      return null;
    }
  },

  mapSupabaseData(data: any[]): RedeemCode[] {
    return data.map(d => ({
      code: d.code,
      reward: d.reward || 'Garena Reward',
      server: d.region,
      category: d.category || 'Bundle',
      slug: d.slug || d.code.toLowerCase(),
      status: (d.status as 'Working' | 'Limited' | 'Expired') || 'Working',
      lastTested: 'Cloud Verified',
      probability: d.probability || 99,
      citations: Array.isArray(d.citations) ? d.citations : [],
      recentClaims: d.recent_claims || 0,
      likes: d.likes || 0
    }));
  },

  async broadcastCodes(region: string, hourKey: string, codes: RedeemCode[]) {
    if (!supabase) return;

    try {
      const formatted = codes.map(c => ({
        code: c.code,
        reward: c.reward,
        region: region,
        hour_key: hourKey,
        category: c.category || 'Bundle',
        slug: c.slug,
        status: c.status,
        probability: c.probability,
        recent_claims: c.recentClaims || Math.floor(Math.random() * 500) + 100,
        likes: c.likes || Math.floor(Math.random() * 200) + 50,
        // Citations are passed as an object array for JSONB support
        citations: c.citations || []
      }));

      // Using upsert to prevent duplicates
      const { error } = await supabase.from('redeem_codes').upsert(formatted, { onConflict: 'slug' });
      if (error) console.error("[Supabase Broadcast Error]", error);
      
      await supabase.from('sync_logs').insert({ region, hour_key: hourKey });
    } catch (e) {
      // Silent fail - storageService handles the local fallback
    }
  }
};
